apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-event-auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 66-228-63-42.ip.linodeusercontent.com
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: music-event-auth-service
                port:
                  number: 80